version: '3'
services:
  game_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        botNickName: "BOT"
        gameUri: "gamehost:1111"
    container_name: "BOT"
    hostname: default
  game:
    build:
      context: C:\JAVA\SpringBootHello\Game
      dockerfile: Dockerfile
    hostname: default
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Game
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8881"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Game
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"