version: '3'


services:
  game_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      botNickName: "BOT"
      server-url: "http://game:8881"
    container_name: "BOT"
    hostname: BOT

  game_bot1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      botNickName: "BOT1"
      server-url: "http://game:8881"
    container_name: "BOT1"
    hostname: BOT1

  game:
    build:
      context: C:\JAVA\SpringBootHello\Game
      dockerfile: Dockerfile
    hostname: GAME
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Game
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8881:8881"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Game
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


